version: '3.1'
services:
  db:
    image: mariadb:10.1
    container_name: db
    restart: always
    volumes:
      - ./mysql/data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

  php:
    build: ./
    container_name: php
    restart: always
    volumes:
      - ./www/:/var/www/html
    ports:
      - "9000:9000"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./www/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8808:80